- name: Install httpd
  yum:
    name: httpd
    state: present
  become: true

- name: start the httpd
  service:
    name: httpd
    state: started
  become: true

- name: add test file
  lineinfile: 
    path: /var/www/html/index.html
    line: pakathama
    create: yes
  become: true 
